-- QUERIES AND DDL's WERE MADE THINKING IN POSTGRES ENVIRONMENT
-- AN RUNNING TEST CAN BE FOUND ON:
--- https://www.db-fiddle.com/f/4jyoMCicNSZpjMt4jFYoz5/128
SELECT a.*,
	SUM(AMOUNT) as TRANSFERRED_AMOUNT
	FROM accounts a
    INNER JOIN transfers t ON a.ID = t.SOURCE_ID
	GROUP BY a.FIRST_NAME, a.LAST_NAME, t.TRANSFER_TIME, a.ID
    HAVING SUM(AMOUNT) > 1000
    AND TRANSFER_TIME >= '2019-01-01'
    ORDER BY TRANSFERRED_AMOUNT DESC;